=== uo269871/sew_22_23/xml/Ejercicio-1/Tarea-5/red_social.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/red_social" elementFormDefault="qualified" targetNamespace="http://tempuri.org/red_social" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="red_social">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="amigo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="amigo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nacimiento" />
				<xs:element ref="residencia" />
				<xs:sequence minOccurs="0" maxOccurs="1">
					<xs:element ref="amigo" />
					<xs:element ref="amigo" />
					<xs:element ref="amigo" />
				</xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="fotografia" />
				<xs:element minOccurs="0" maxOccurs="1" ref="video" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="apellidos" type="xs:string" use="required" />
			<xs:attribute name="comentarios" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="nacimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
			<xs:attribute name="lugar" type="xs:string" use="required" />
			<xs:attribute name="fecha" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="residencia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
			<xs:attribute name="lugar" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="lat" type="xs:string" use="required" />
					<xs:attribute name="long" type="xs:string" use="required" />
					<xs:attribute name="alt" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="url" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="url" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uo269871/sew_22_23/xml/Ejercicio-1/Tarea-4/red_social.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE red_social>
<red_social xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="red_social.xsd">
    <amigo nombre="Miguel" apellidos="Menendez Rodriguez" comentarios="Estudiante"> 
        <nacimiento lugar="Oviedo" fecha="2000-08-29">
            <coordenadas lat="43.354933" long="-5.8514295" alt="259.9078972"/>
        </nacimiento>
        <residencia lugar="Caboalles de Abajo">
                        <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                    </residencia>
        <fotografia url = "miguel.jpg"/>
        <amigo nombre="Ana Maria" apellidos="Palomero Pescador" comentarios="Huérfana de padre">
            <nacimiento lugar="Caboalles de Abajo" fecha="1917-12-03">
                <coordenadas lat="42.9521477" long="-6.374352" alt="1.044.0396361"/>
            </nacimiento>
            <residencia lugar="Caboalles de Abajo">
                <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
            </residencia>
            <fotografia url = "anamari.jpg"/>
            <amigo nombre="Javier" apellidos="Menendez Jimenez" comentarios="Ganadero">
                <nacimiento lugar="Helgueras" fecha="1916-04-17">
                    <coordenadas lat="43.3563116" long="-5.1206803" alt="199.8421655"/>
                </nacimiento>
                <residencia lugar="Cangas de Onís">
                    <coordenadas lat="43.3507281" long="-5.1287966" alt="66.3388045"/>
                </residencia>
                <fotografia url = "javier.jpg"/>
            </amigo>
            <amigo nombre="Lucia" apellidos="Gutierrez Guanes" comentarios="Ganadera">
                <nacimiento lugar="Celango" fecha="1919-12-28">
                    <coordenadas lat="43.3567593" long="-5.112205" alt="299.7768765"/>
                </nacimiento>
                <residencia lugar="Cangas de Onís">
                    <coordenadas lat="43.3507281" long="-5.1287966" alt="66.3388045"/>
                </residencia>
                <fotografia url = "lucia.jpg"/>
            </amigo>
            <amigo nombre="Alejandro" apellidos="Fernandez Varela" comentarios="Agricultor">
                <nacimiento lugar="San Juan de Parres" fecha="1918-06-20">
                    <coordenadas lat="43.3546285" long="-5.1478346" alt="168.933651"/>
                </nacimiento>
                <residencia lugar="San Juan de Parres">
                    <coordenadas lat="43.3546285" long="-5.1478346" alt="168.933651"/>
                </residencia>
                <fotografia url = "alex.jpg"/>
            </amigo>
        </amigo> 
        <amigo nombre="Luis" apellidos="Menendez Fernandez" comentarios="Padre"> 
            <nacimiento lugar="Oviedo" fecha="1970-12-11">
                <coordenadas lat="43.363433" long="-5.8633631" alt="257.1425868"/>
            </nacimiento>
            <residencia lugar="Caboalles de Abajo">
                <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>        
            </residencia>
            <fotografia url = "luis.jpg"/>
            <amigo nombre="Manuel" apellidos="Menendez Gutierrez" comentarios="Primer universitario">
                <nacimiento lugar="Cangas de Onís" fecha="1941-07-29">
                    <coordenadas lat="43.3507281" long="-5.1287966" alt="66.3388045"/>
                </nacimiento>
                <residencia lugar="Caboalles de Abajo">
                        <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                </residencia>
                <fotografia url = "manuel.jpg"/>        
            </amigo>
            <amigo nombre="Maria Concepcion" apellidos="Fernanez Garcia" comentarios="Propietaria de una tienda">
                <nacimiento lugar="San Juan de Parres" fecha="1943-05-13">
                    <coordenadas lat="43.3546285" long="-5.1478346" alt="168.933651"/>
                </nacimiento>
                <residencia lugar="Caboalles de Abajo">
                        <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                </residencia>
                <fotografia url = "concha.jpg"/>     
            </amigo>
            <amigo nombre="Laura" apellidos="Garcia Delgado" comentarios="Agricultora">
                <nacimiento lugar="San Juan de Parres" fecha="1918-01-14">
                    <coordenadas lat="43.3539544" long="-5.1482913" alt="158.8678707"/>
                </nacimiento>
                <residencia lugar="San Juan de Parres">
                    <coordenadas lat="43.3546285" long="-5.1478346" alt="168.933651"/>
                </residencia>
                <fotografia url = "laura.jpg"/>
            </amigo>
        </amigo>
        <amigo nombre="Ana" apellidos="Rodriguez Garcia" comentarios="Madre">
            <nacimiento lugar="Villablino" fecha="1972-11-21">
                <coordenadas lat="42.9449357" long="-6.3295471" alt="1.037.5875016"/>
            </nacimiento>
            <residencia lugar="Caboalles de Abajo">
                        <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
            </residencia>
            <fotografia url = "ana.jpg"/>
            <amigo nombre="Maria Jose" apellidos="Garcia Palomero" comentarios="Hija única">
                <nacimiento lugar="Caboalles de Abajo" fecha="1920-02-14">
                    <coordenadas lat="42.9521477" long="-6.374352" alt="1.044.0396361"/>
                </nacimiento>
                <residencia lugar="Caboalles de Abajo">
                        <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                </residencia>
                <fotografia url = "marijo.jpg"/>
            </amigo>
            <amigo nombre="Jose Maria" apellidos="Garcia Marrero" comentarios="Minero">
                <nacimiento lugar="Caboalles de Abajo" fecha="1920-02-14">
                    <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                </nacimiento>
                <residencia lugar="Caboalles de Abajo">
                    <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                </residencia>
                <fotografia url = "josemari.jpg"/>
            </amigo>
            <amigo nombre="Munia" apellidos="Valle Dominguez" comentarios="Madre de tres hijos">
                <nacimiento lugar="Llamas de Laciana" fecha="1920-10-25">
                    <coordenadas lat="42.9285463" long="-6.3223696" alt="994.4560698"/>
                </nacimiento>
                <residencia lugar="Caboalles de Abajo">
                    <coordenadas lat="42.9526827" long="-6.3755552" alt="1.054.7566915"/>
                </residencia>
                <fotografia url = "munia.jpg"/>
            </amigo>
        </amigo>
    </amigo>
</red_social>
